name: Beta CI-CD Workflow

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  id-token: write

jobs:
  ci-cd:
    name: CI-CD Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Build Application
        run: pnpm run build
      
      - name: Run Tests
        run: pnpm run test

      - name: Publish to NPM
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          echo ${{ github.ref }} = refs/heads/beta

          if [ ${{ github.ref }} = refs/heads/beta  ]; then
            pnpx lerna version --conventional-prerelease --preid beta
          else
            pnpx lerna version --conventional-graduate
          fi

          pnpx lerna publish from-git

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}